



import {
  Special_Gothic
} from "next/font/google";
import "../globals.css";
import Providers from "../(mainlayout)/provider";
import Curtain from "./about/Componenets/Shared/Curtain";
import Header from "./about/Componenets/Fixed/Header";


const geistSans = Special_Gothic
  ({
    weight: ["400", "500", "600", "700"]
  });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <Providers>
          
          <Header></Header>
          <Curtain></Curtain>
          {children}
        </Providers>
      </body>
    </html>
  );
}
